SELECT DISTINCT ?work WHERE {
  { ?work wdt:P31 wd:Q571 . } # book
  UNION { ?work wdt:P31 wd:Q2831984 . } # comic book album
  UNION { ?work wdt:P31 wd:Q1004 . } # bande dessinée / comic book
  UNION { ?work wdt:P31 wd:Q1760610 . } # comic book
  UNION { ?work wdt:P31 wd:Q8261 . } # novel / roman
  UNION { ?work wdt:P31 wd:Q25379 . } # theatre play
  UNION { ?work wdt:P31 wd:Q386724 . } # work
  UNION { ?work wdt:P31 wd:Q49084 . } # short story / conte
  UNION { ?work wdt:P31 wd:Q8274 . } # manga
  UNION { ?work wdt:P31 wd:Q17518461 . } # posthumous work
}
