#!/usr/bin/env sh
set -eu

# env "PATH=$PATH" alows to access add-to-systemd in sudo mode
sudo env "PATH=$PATH" add-to-systemd \
   --env NODE_ENV=production \
   --env FORCE_COLOR=true \
   --env PATH="$PATH" \
   wsse "$(which coffee) $(pwd)/server/server.coffee"
