#!/usr/bin/env zsh
set -eu

source ./scripts/lib/import_export_commons

import_index_base(){
  index=$1
  type=$2
  name="${index}_${type}"
  input="${dump_folder}/${name}.json"

  echo -e "\e[0;30mdecompressing ${name}\e[0m"
  pigz --keep --decompress "${input}.gz"

  echo -e "\e[0;30mimporting ${name}\e[0m"

  elasticdump \
    --input="$input" \
    --output="${es_host}/${index}" \
    --type="$type"

  echo -e "\e[0;32mdone importing ${name}\e[0m"
}

import_index(){
  index=$1
  import_index_base "$index" 'mapping'
  import_index_base "$index" 'data'
}

import_index "$inv_entities_index"
import_index "$wd_entities_index"
